### PR TITLE
Onboarding etiquette

### LINKED ISSUE #2: Welcome protocol
We’ll socialise and introduce new members when they join. They’ll get a warm welcome on the app, as well as a welcome email with some helpful tips.

- [ ] template copy for #introduction welcome message
- [ ] template copy for welcome email
- [ ] try it out / test it!

Some things to include in the messaging:

- Introduce the person who you invited
- What did I miss CTA?
- Calendly link to schedule call?
- How do we do things?
- Vision + name + avatar
- Want to get involved?

### PR DESCRIPTION
**Pull request by tillkruss**
Resolves #2.

### CODE REVIEW

**Comment by mattwynne** [comment]
Good start!

Are we intending this to be read and referenced/used by existing members? If so, should we include details about how to get an invite link? I'm not sure how that works if you're not a mod.

I think we could add a step for the introducer to (privately?) encourage the invitee to fill out their bio and profile picture _before_ they send out the introduction.

We could add some links to examples of intro posts:

https://nelson.social/@matt/109467858887332318
https://nelson.social/@matt/109448612035209109
https://nelson.social/@matt/109447258921683383
https://nelson.social/@matt/109447258921683383

**Comment by tillkruss** [comment]
> Are we intending this to be read and referenced/used by existing members? If so, should we include details about how to get an invite link? I'm not sure how that works if you're not a mod.

I added an invite link.

**Comment by tillkruss** [comment]
> I think we could add a step for the introducer to (privately?) encourage the invitee to fill out their bio and profile picture _before_ they send out the introduction.

Added.

**Comment by tillkruss** [comment]
@blaine @mattwynne Can I get a final review before merging this?

**Review by mattwynne — APPROVED** [review]

**Pull request merged**
